import shutil
import subprocess
from pathlib import Path
from typing import Any

import pytest

from apidiom.generate.codegen import (
    CodegenError,
    choose_codegen_tier,
    generate_client_code,
)
from apidiom.ingest.openapi_ingest import normalize_openapi_document


def _small_spec() -> dict[str, Any]:
    return {
        "openapi": "3.1.0",
        "info": {"title": "Tiny API", "version": "1.0.0"},
        "paths": {
            "/pets/{petId}": {
                "get": {
                    "operationId": "getPet",
                    "parameters": [
                        {
                            "name": "petId",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "integer"},
                        },
                        {
                            "name": "includeToys",
                            "in": "query",
                            "required": False,
                            "schema": {"type": "boolean"},
                        },
                    ],
                    "responses": {
                        "200": {
                            "description": "OK",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/Pet"}
                                }
                            },
                        }
                    },
                }
            },
            "/pets": {
                "post": {
                    "operationId": "createPet",
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Pet"}
                            }
                        }
                    },
                    "responses": {"201": {"description": "Created"}},
                }
            },
        },
        "components": {
            "schemas": {
                "Pet": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "integer"},
                        "name": {"type": "string"},
                    },
                }
            }
        },
    }


def test_tier_selection_prefers_primary_when_java_and_cli_present() -> None:
    tier = choose_codegen_tier(
        mode="auto",
        has_openapi_generator=lambda: True,
        has_java=lambda: True,
    )

    assert tier == "openapi-generator"


def test_tier_selection_uses_fallback_when_java_absent() -> None:
    tier = choose_codegen_tier(
        mode="auto",
        has_openapi_generator=lambda: True,
        has_java=lambda: False,
    )

    assert tier == "builtin"


def test_primary_success_returns_generated_output() -> None:
    spec = _small_spec()
    model = normalize_openapi_document(spec, "test")
    output_dir = Path("tests/fixtures/generated-primary-success")
    if output_dir.exists():
        shutil.rmtree(output_dir)

    def runner(
        cmd: list[str],
        *,
        capture_output: bool,
        text: bool,
        check: bool,
    ) -> subprocess.CompletedProcess[str]:
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "client.py").write_text("# generated by tool\n", encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="ok", stderr="")

    result = generate_client_code(
        spec,
        model,
        mode="openapi-generator",
        output_dir=output_dir,
        runner=runner,
        has_openapi_generator=lambda: True,
        has_java=lambda: True,
    )

    assert result.tier == "openapi-generator"
    assert result.files["client.py"] == "# generated by tool\n"
    assert "# generated by tool" in result.client_text
    shutil.rmtree(output_dir)


def test_primary_failure_surfaces_stderr_and_cleans_output_dir() -> None:
    spec = _small_spec()
    model = normalize_openapi_document(spec, "test")
    output_dir = Path("tests/fixtures/generated-primary-failure")
    if output_dir.exists():
        shutil.rmtree(output_dir)

    def runner(
        cmd: list[str],
        *,
        capture_output: bool,
        text: bool,
        check: bool,
    ) -> subprocess.CompletedProcess[str]:
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "partial.py").write_text("partial", encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="tool failed")

    with pytest.raises(CodegenError, match="tool failed"):
        generate_client_code(
            spec,
            model,
            mode="openapi-generator",
            output_dir=output_dir,
            runner=runner,
            has_openapi_generator=lambda: True,
            has_java=lambda: True,
        )

    assert not output_dir.exists()


def test_forced_openapi_generator_unavailable_fails_fast() -> None:
    spec = _small_spec()
    model = normalize_openapi_document(spec, "test")

    with pytest.raises(CodegenError, match="Install Java and openapi-generator-cli"):
        generate_client_code(
            spec,
            model,
            mode="openapi-generator",
            has_openapi_generator=lambda: False,
            has_java=lambda: False,
        )


def test_fallback_generates_models_and_httpx_wrappers() -> None:
    spec = _small_spec()
    model = normalize_openapi_document(spec, "test")

    result = generate_client_code(
        spec,
        model,
        mode="builtin",
        model_generator=lambda spec_json: (
            "from pydantic import BaseModel\n\nclass Pet(BaseModel):\n    id: int\n"
        ),
    )

    assert result.tier == "builtin"
    assert "class Pet(BaseModel)" in result.client_text
    assert "def get_pet(" in result.client_text
    assert 'path = f"/pets/{petId}"' in result.client_text
    assert 'client.request(\n        "GET",' in result.client_text
    assert "def create_pet(" in result.client_text
    assert 'path = "/pets"' in result.client_text
    assert 'client.request(\n        "POST",' in result.client_text


def test_unknowns_propagate_into_generated_code_comments() -> None:
    spec = _small_spec()
    parameter = spec["paths"]["/pets/{petId}"]["get"]["parameters"][1]
    parameter["x-apidiom-unknown"] = ["required"]
    parameter["description"] = "UNVERIFIED: required not specified"
    model = normalize_openapi_document(spec, "test")

    result = generate_client_code(
        spec,
        model,
        mode="builtin",
        model_generator=lambda spec_json: "",
    )

    assert "# UNVERIFIED: required not specified in docs" in result.client_text
    assert "# UNVERIFIED: UNVERIFIED: required not specified" in result.client_text
