import type { APIEndpoint, APIModel, AuthConfig, OpenAPIParam } from "../model";

export interface MCPGenOptions {
  tags?: string[];
  include?: string[];
  groupByTag?: boolean;
}

export function normalizeToolName(operationId: string): string {
  // Strip standalone version segments like V1, V2, V10
  let name = operationId.replace(/V\d+/g, "");
  // PascalCase/camelCase → snake_case
  name = name
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z\d])([A-Z])/g, "$1_$2")
    .toLowerCase()
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
  return name || operationId.toLowerCase();
}

export function enrichDescription(
  summary: string | undefined,
  description: string | undefined,
  params: OpenAPIParam[]
): string {
  const parts: string[] = [];

  const cleanSummary = summary?.replace(/\.$/, "").trim();
  if (cleanSummary) parts.push(cleanSummary);

  if (description) {
    const firstSentence = description.split(/\.\s+/)[0].replace(/\.$/, "").trim();
    if (firstSentence && firstSentence !== cleanSummary) {
      parts.push(firstSentence);
    }
  }

  const requiredParams = params.filter(
    (p) => p.required && (p.in === "path" || p.in === "query")
  );
  if (requiredParams.length > 0) {
    parts.push(`Params: ${requiredParams.map((p) => `${p.name} (required)`).join(", ")}`);
  }

  return parts.length > 0 ? parts.join(". ") + "." : "";
}

function deduplicateNames(names: string[]): string[] {
  const seen: Record<string, number> = {};
  return names.map((name) => {
    const count = seen[name] ?? 0;
    seen[name] = count + 1;
    return count === 0 ? name : `${name}_${count + 1}`;
  });
}

export function generateMCPServer(
  model: APIModel,
  auth: AuthConfig[],
  opts: MCPGenOptions = {}
): string {
  const endpoints = filterEndpoints(model.endpoints, opts);
  const serverName = toSlug(model.title);

  // Pre-compute normalized tool names and deduplicate
  const rawNames = endpoints.map((ep) => {
    const base = normalizeToolName(ep.operationId);
    if (opts.groupByTag && ep.tags.length > 0) {
      return `${ep.tags[0]}__${base}`;
    }
    return base;
  });
  const names = deduplicateNames(rawNames);

  // Warn on stderr if any names were renamed due to collision
  rawNames.forEach((raw, i) => {
    if (names[i] !== raw) {
      process.stderr.write(
        `Warning: duplicate tool name "${raw}" renamed to "${names[i]}"\n`
      );
    }
  });

  const parts: string[] = [
    `"use strict";`,
    `// Generated by apidiom — https://github.com/poyhi/apidiom`,
    `// ${model.title} v${model.version}`,
    ``,
    `const https = require("https");`,
    `const http = require("http");`,
    ``,
    generateAuthSection(auth),
    generateRequestHelper(),
    generateToolsArray(endpoints, names, model.serverUrl, auth),
    generateMCPHandler(serverName, model.version),
  ];

  return parts.filter((s) => s !== null && s !== undefined).join("\n");
}

function filterEndpoints(endpoints: APIEndpoint[], opts: MCPGenOptions): APIEndpoint[] {
  let result = endpoints;
  if (opts.tags && opts.tags.length > 0) {
    result = result.filter((e) => e.tags.some((t) => opts.tags!.includes(t)));
  }
  if (opts.include && opts.include.length > 0) {
    result = result.filter((e) => opts.include!.includes(e.operationId));
  }
  return result;
}

function generateAuthSection(auth: AuthConfig[]): string {
  if (auth.length === 0) return "";
  const lines: string[] = [`// --- Auth ---`];
  for (const a of auth) {
    lines.push(
      `const ${a.envVar} = process.env.${a.envVar};`,
      `if (!${a.envVar}) { process.stderr.write("Missing required env var: ${a.envVar}\\n"); process.exit(1); }`
    );
  }
  lines.push(``);
  return lines.join("\n");
}

function generateRequestHelper(): string {
  return `// --- HTTP helper ---
function _request(method, url, headers, body) {
  return new Promise(function(resolve, reject) {
    var u = new URL(url);
    var lib = u.protocol === "https:" ? https : http;
    var opts = {
      hostname: u.hostname,
      port: u.port || undefined,
      path: u.pathname + u.search,
      method: method,
      headers: Object.assign({}, body !== undefined ? { "Content-Type": "application/json" } : {}, headers)
    };
    var req = lib.request(opts, function(res) {
      var d = "";
      res.on("data", function(c) { d += c; });
      res.on("end", function() {
        try { resolve(JSON.parse(d)); } catch(e) { resolve(d); }
      });
    });
    req.on("error", reject);
    if (body !== undefined) req.write(JSON.stringify(body));
    req.end();
  });
}
`;
}

function generateToolsArray(
  endpoints: APIEndpoint[],
  names: string[],
  serverUrl: string,
  auth: AuthConfig[]
): string {
  const tools = endpoints.map((ep, i) => generateTool(ep, names[i], serverUrl, auth));
  return `// --- Tools ---\nvar _TOOLS = [\n${tools.join(",\n")}\n];\n`;
}

function generateTool(
  ep: APIEndpoint,
  toolName: string,
  serverUrl: string,
  auth: AuthConfig[]
): string {
  const pathParams = ep.parameters.filter((p) => p.in === "path");
  const queryParams = ep.parameters.filter((p) => p.in === "query");

  const schemaProps: Record<string, unknown> = {};
  const required: string[] = [];

  for (const p of ep.parameters) {
    if (p.in === "path" || p.in === "query") {
      schemaProps[p.name] = { ...(p.schema as object), description: p.description };
      if (p.required) required.push(p.name);
    }
  }
  if (ep.requestBody) {
    schemaProps["body"] = {
      type: "object",
      description: ep.requestBody.description ?? "Request body",
    };
    if (ep.requestBody.required) required.push("body");
  }

  const headerAuth = auth.filter((a) => !a.queryParam);
  const queryAuth = auth.filter((a) => a.queryParam);

  const authHeaderEntries = headerAuth.map((a) => {
    const headerValue = buildHeaderValue(a);
    return `      ${JSON.stringify(a.headerName)}: ${headerValue}`;
  });
  const authHeadersStr =
    authHeaderEntries.length > 0
      ? `{\n${authHeaderEntries.join(",\n")}\n    }`
      : "{}";

  const urlParts = buildUrlParts(serverUrl, ep.path, pathParams);

  const queryLines: string[] = [];
  queryLines.push(`    var _q = new URLSearchParams();`);
  for (const p of queryParams) {
    queryLines.push(
      `    if (args[${JSON.stringify(p.name)}] !== undefined) _q.set(${JSON.stringify(p.name)}, String(args[${JSON.stringify(p.name)}]));`
    );
  }
  for (const a of queryAuth) {
    queryLines.push(`    _q.set(${JSON.stringify(a.queryParam)}, ${a.envVar});`);
  }
  queryLines.push(`    var _qs = _q.toString() ? "?" + _q.toString() : "";`);

  const bodyArg = ep.requestBody ? `args["body"]` : "undefined";
  const urlExpr = `(${urlParts}) + _qs`;

  const description = enrichDescription(ep.summary, ep.description, ep.parameters);

  return `  {
    name: ${JSON.stringify(toolName)},
    description: ${JSON.stringify(description)},
    inputSchema: ${JSON.stringify({ type: "object", properties: schemaProps, required })},
    call: function(args) {
${queryLines.join("\n")}
      return _request(${JSON.stringify(ep.method)}, ${urlExpr}, ${authHeadersStr}, ${bodyArg});
    }
  }`;
}

/**
 * Build a JS expression (string concatenation) for the URL with path params substituted.
 * e.g. serverUrl="/v2" path="/pets/{petId}" -> '"https://host/v2/pets/" + args["petId"]'
 */
function buildUrlParts(serverUrl: string, path: string, pathParams: APIEndpoint["parameters"]): string {
  if (pathParams.length === 0) {
    return JSON.stringify(serverUrl + path);
  }

  // Split path by {paramName} placeholders
  const segments: string[] = [];
  let remaining = serverUrl + path;
  const paramPattern = /\{([^}]+)\}/;
  let match: RegExpExecArray | null;

  while ((match = paramPattern.exec(remaining)) !== null) {
    const before = remaining.slice(0, match.index);
    const paramName = match[1];
    if (before) segments.push(JSON.stringify(before));
    segments.push(`String(args[${JSON.stringify(paramName)}])`);
    remaining = remaining.slice(match.index + match[0].length);
  }
  if (remaining) segments.push(JSON.stringify(remaining));

  return segments.join(" + ");
}

/**
 * Build a JS expression for the header value.
 * headerFormat is like "{value}" or "Bearer {value}".
 * We replace {value} with the env var reference.
 */
function buildHeaderValue(auth: AuthConfig): string {
  const format = auth.headerFormat;
  if (format === "{value}") {
    return auth.envVar;
  }
  // e.g. "Bearer {value}" -> '"Bearer " + STRIPE_BEARER_TOKEN'
  const parts = format.split("{value}");
  const result: string[] = [];
  for (let i = 0; i < parts.length; i++) {
    if (parts[i]) result.push(JSON.stringify(parts[i]));
    if (i < parts.length - 1) result.push(auth.envVar);
  }
  return result.join(" + ");
}

function generateMCPHandler(serverName: string, version: string): string {
  return `// --- MCP Protocol ---
var _buf = "";
process.stdin.setEncoding("utf8");
function _processLine(line) {
  if (!line.trim()) return;
  var msg;
  try { msg = JSON.parse(line); } catch(e) { return; }
  _handle(msg).catch(function(e) { process.stderr.write(e.message + "\\n"); });
}
process.stdin.on("data", function(chunk) {
  _buf += chunk;
  var lines = _buf.split("\\n");
  _buf = lines.pop() || "";
  for (var i = 0; i < lines.length; i++) { _processLine(lines[i]); }
});
process.stdin.on("end", function() {
  if (_buf.trim()) _processLine(_buf);
});

function _send(obj) { process.stdout.write(JSON.stringify(obj) + "\\n"); }

function _handle(msg) {
  var id = msg.id;
  var method = msg.method;
  var params = msg.params;
  if (method === "initialize") {
    _send({ jsonrpc: "2.0", id: id, result: { protocolVersion: "2024-11-05", capabilities: { tools: {} }, serverInfo: { name: ${JSON.stringify(serverName)}, version: ${JSON.stringify(version)} } } });
    return Promise.resolve();
  } else if (method === "notifications/initialized") {
    return Promise.resolve();
  } else if (method === "tools/list") {
    _send({ jsonrpc: "2.0", id: id, result: { tools: _TOOLS.map(function(t) { return { name: t.name, description: t.description, inputSchema: t.inputSchema }; }) } });
    return Promise.resolve();
  } else if (method === "tools/call") {
    var toolName = params && params.name;
    var tool = null;
    for (var i = 0; i < _TOOLS.length; i++) {
      if (_TOOLS[i].name === toolName) { tool = _TOOLS[i]; break; }
    }
    if (!tool) {
      _send({ jsonrpc: "2.0", id: id, error: { code: -32601, message: "Unknown tool: " + toolName } });
      return Promise.resolve();
    }
    return Promise.resolve(tool.call((params && params.arguments) || {})).then(function(result) {
      _send({ jsonrpc: "2.0", id: id, result: { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] } });
    }).catch(function(e) {
      _send({ jsonrpc: "2.0", id: id, result: { content: [{ type: "text", text: "Error: " + e.message }], isError: true } });
    });
  } else if (id !== undefined) {
    _send({ jsonrpc: "2.0", id: id, error: { code: -32601, message: "Method not found: " + method } });
    return Promise.resolve();
  }
  return Promise.resolve();
}
`;
}

function toSlug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
